# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: |
            yarn install
            yarn run buildFaq
            yarn run buildIndex

      - run:
          command: |
            git config --global user.email "oso.network.ci@gmail.com"
            git config --global user.name "OSOCi"
            git add index.html
            git commit -m "CI Built index.html from partials [ci skip]"
            git push
